# Generated by Django 6.0.1 on 2026-03-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_brand_product_is_featured_product_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deal_of_day',
            field=models.BooleanField(default=False),
        ),
    ]
