# Generated by Django 6.0.1 on 2026-03-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_deal_of_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
